### ISSUE TITLE
大佬 不知道为什么无法设置电影墙和背景图

### ISSUE THREAD

**Issue by DemonJimmy** [Carseason/routerdog#10]
![image](https://github.com/Carseason/routerdog/assets/25766523/15bdb494-d35f-4cfc-bfe4-805958a51b44)
![image](https://github.com/Carseason/routerdog/assets/25766523/6fa09945-f503-438f-b30e-eeec9235e8ad)
![image](https://github.com/Carseason/routerdog/assets/25766523/caa46b62-2d8a-4d47-bb65-0e69a35d878a)

**Comment by Carseason** [comment]
url后面的/删掉试一下

**Comment by xmasrain** [comment]
> url后面的/删掉试一下

正解，实测有效！8096后面不能加"/"

**Comment by hupo376787** [comment]
> url后面的/删掉试一下

背景图无法设置
