### ISSUE TITLE
找不到ipk的独立安装包

### ISSUE THREAD

**Issue by zjyg1993** [Carseason/routerdog#17]
目前只有istore上的商店有路由狗的安装入口，但是在github上没有ipk的下载包自行安装，以后能一起随行提供一份吗，这样我们不用istore的op固件也能体验路由狗的界面

**Comment by Carseason** [comment]
这里可以下载到： https://github.com/Carseason/openwrt-app-actions/actions
也可以自编译 https://github.com/Carseason/openwrt-packages
但是里面的功能还是依赖 istoreos 的 quickstart和istore商店的

**Comment by zjyg1993** [comment]
邮件收到，我待会看完，马上就回复你-----------------------------------------------------From Jerome
