### ISSUE TITLE
路由狗 1.0.4 网络状态-DHCP列表不显示设备名称，这样其实很不方便，建议修复~

### ISSUE THREAD

**Issue by xmasrain** [Carseason/routerdog#19]
![image](https://github.com/Carseason/routerdog/assets/58833842/d569bf24-5e57-41fd-abe0-a4470685dfcc)

**Comment by Carseason** [comment]
下一步会改成arp和dchp混合还有wol网络唤醒

**Comment by Carseason** [comment]
1.0.6已实现
