### ISSUE TITLE
电影墙打不开

### ISSUE THREAD

**Issue by cocollin1** [Carseason/routerdog#2]
大佬，电影墙打不开，提示jellyfin连接超时

**Comment by Carseason** [comment]
配置jellyfin的apikey

**Comment by cocollin1** [comment]
都配置好了，链接超时

**Comment by Carseason** [comment]
截个图看看？

**Comment by cocollin1** [comment]
![issue1](https://github.com/Carseason/routerdog/assets/142299520/3e7add25-e2be-4357-bf1d-a14140122e90)
![issue2](https://github.com/Carseason/routerdog/assets/142299520/103f7794-7802-450b-adbd-16c9d012cfd7)

**Comment by Carseason** [comment]
方便进QQ群吗？

**Comment by cocollin1** [comment]
已添加，麻烦通过下
