### ISSUE TITLE
以前版本路由狗自带电影墙很好用，希望下一版本把这个功能加上 

### ISSUE THREAD

**Issue by 5373648** [Carseason/routerdog#22]
以前版本路由狗自带电影墙配合jellyfin很好用，希望下一版本把这个功能加上

**Comment by Carseason** [comment]
和直接使用jellyfin的区别是？
我想的是同端口使用，但是 uhttpd 的限制导致无法做到。

**Comment by Carseason** [comment]
https://github.com/Carseason/routerdog/discussions/23
