### ISSUE TITLE
路由狗界面不能点击高级设置跳转了

### ISSUE THREAD

**Issue by 3322233** [Carseason/routerdog#26]
No page is registered at '/admin/quickstart'. If this url belongs to an extension, make sure it is properly installed. If the extension was recently installed, try removing the /tmp/luci-indexcache file.

**Comment by Carseason** [comment]
你的不是istoreos吧？没安装quickstart才会出现，但是不影响

**Comment by 3322233** [comment]
是的，之前能进更新路由狗后就打不开网页后台了😓cgi-bin/luci/admin/store/pages/installed改成这地址才能进后台了，点击高级设置跳转到这地址就不行/cgi-bin/luci/admin/quickstart/

**Comment by Carseason** [comment]
因为新版本删掉了对quickstar的强制依赖，但是高级设置还是跳转到 quickstart导致的。
你可以自己手动安装一下quickstart 或者等过段时间我更新新版本

**Comment by 3322233** [comment]
感谢回复，软件包貌似刷不出来。只能等更新修复了😅

**Comment by Carseason** [comment]
你截个图看看

**Comment by 3322233** [comment]
![20240309_212309.jpg](https://github.com/Carseason/routerdog/assets/147904531/a5245f80-9717-4238-a685-7346df707136)

![20240309_212252.jpg](https://github.com/Carseason/routerdog/assets/147904531/2858ffa0-e0d4-4321-96b0-8fba7eee22a4)

![20240309_212230.jpg](https://github.com/Carseason/routerdog/assets/147904531/334a8f84-f134-420d-b6c9-b4743c724465)

不知道是不是这插件😂重启还是一样

**Comment by Carseason** [comment]
你安装了 quickstart 还要安装 luci-app-quickstart 的
你可以在 https://github.com/linkease/istore-repo 这里下载到

**Comment by 3322233** [comment]
好的多谢，不过最好还是大佬下次能更新改一下最好。那样有同样问题的就不用在去麻烦了不是么。

**Comment by Carseason** [comment]
https://github.com/Carseason/routerdog/discussions/27
