### ISSUE TITLE
路由狗APP商店界面

### ISSUE THREAD

**Issue by 3322233** [Carseason/routerdog#29]
路由狗APP商店显示不全!
![Screenshot_20240313-174747.jpg](https://github.com/Carseason/routerdog/assets/147904531/0fb0f394-aca5-478f-b24e-940802fb2f0b)

只有卸载 打开按钮被遮挡住了用网页打开没问题

**Comment by Carseason** [comment]
你系统的webview太老了？我这边没问题

**Comment by Carseason** [comment]
也可能是你手机的尺寸太大了, 大于 680px 也可能会出现

**Comment by 3322233** [comment]
> 也可能是你手机的尺寸太大了, 大于 680px 也可能会出现

三星 s8+ 用edge浏览器网页端是正常的😓别的浏览器不行。。。。。![Screenshot_20240314-084554_Edge.jpg](https://github.com/Carseason/routerdog/assets/147904531/db718682-896a-47bb-9fb5-2e1bf904a56d)

**Comment by Carseason** [comment]
你用chrome试试，
或者更新你手机的的webview
