### ISSUE TITLE
路由狗需要映射多少端口？

### ISSUE THREAD

**Issue by vipmato** [Carseason/routerdog#39]
App无法访问路由器，请问路由狗的默认端口为多少？

**Comment by Carseason** [comment]
istoreos的话没有端口，是默认通过unix绑定到luci上的，所以你路由器网页是什么它就是什么

**Comment by vipmato** [comment]
如果跟着网页的话，那就是默认80端口，但是外网访问路由器网页需要外网端口映射内网80端口，APP上没有端口选项，这个就不好办了，因为我的网络是公网的，其他NAS也绑定了DDNS，想用APP连接该域名进行访问路由狗

**Comment by Carseason** [comment]
你映射加上端口不就好了，比如 http://xxx.xxx.com:8888

**Comment by vipmato** [comment]
这么简单的操作自己想复杂了😂，搞定了，感谢，期待出IOS版本
