### ISSUE TITLE
我的影院找不到配置的位置

### ISSUE THREAD

**Issue by JadynWong** [Carseason/routerdog#41]
![Clip_2024-04-19_02-28-36](https://github.com/Carseason/routerdog/assets/13699353/0c33dca6-91ec-4e64-b810-6fbdae05aa6a)

版本v1.3.1
请问在哪里可以配置Jellyfin地址和ApiKey?

**Comment by Carseason** [comment]
走的内部转发，你配置好jellyfin后点重新加载配置应该就可以了。
如果不行，就重启一下

**Comment by Carseason** [comment]
或者
```
/etc/init.d/routergo restart
```

**Comment by JadynWong** [comment]
感谢, 已经工作, 之前是自己手动run jellyfin容器, 没有使用iStoreOS的配置
