### ISSUE TITLE
6.1.25内核不能安装嘛？

### ISSUE THREAD

**Issue by 392377870** [Carseason/routerdog#6]
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-md-mod
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-md-mod found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-md-raid0
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-md-raid0 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-md-raid10
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-md-raid10 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-md-raid1
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-md-raid1 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-crypto-hash
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-crypto-null
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-crypto-aead
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-crypto-manager
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-crypto-authenc
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for app-meta-routerdog:
 *      kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885)
 * opkg_install_cmd: Cannot install package app-meta-routerdog.

**Comment by Carseason** [comment]
你这个能固件能安装 istore应用商店和 quickstart 吗？ 
应该是这两个其中的依赖满足不了

**Comment by 392377870** [comment]
> 你这个能巩固能力安装istore应用商店和快速入门吗？ 应该是这两个其中的依赖不能满足

Lean源码自己编译的，istore商店已集成到固件，quickstart还不清楚是什麽

**Comment by 392377870** [comment]
> 你这个能巩固能力安装istore应用商店和快速入门吗？ 应该是这两个其中的依赖不能满足

Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libstdcpp6 and libstdcpp6) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libstdcpp6 and libstdcpp6) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Installing app-meta-routerdog (0.0.19-1) to root...
Downloading https://istore.linkease.com/repo/all/meta/app-meta-routerdog_0.0.19-1_all.ipk
Multiple packages (libstdcpp6 and libstdcpp6) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libstdcpp6 and libstdcpp6) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-md-mod
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-md-mod found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-md-raid0
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-md-raid0 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-md-raid10
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-md-raid10 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-md-raid1
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-md-raid1 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-crypto-hash
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-crypto-null
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-crypto-aead
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-crypto-manager
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-crypto-authenc
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for app-meta-routerdog:
 *      kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885)
 * opkg_install_cmd: Cannot install package app-meta-routerdog.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    57  100    57    0     0    282      0 --:--:-- --:--:-- --:--:--   285
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124  100   124    0     0    576      0 --:--:-- --:--:-- --:--:--   582
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   146  100   146    0     0    683      0 --:--:-- --:--:-- --:--:--   688
Downloading https://istore.linkease.com/repo/all/nas_luci/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_nas_luci
Downloading https://istore.linkease.com/repo/all/store/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_store
Downloading https://istore.linkease.com/repo/aarch64_cortex-a53/nas/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_nas
Downloading https://istore.linkease.com/repo/all/compat/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/istore_compat
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/targets/rockchip/armv8/packages/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_core
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/base/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_base
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/helloworld/Packages.gz
*** Failed to download the package list from https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/helloworld/Packages.gz

Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/istore/Packages.gz
*** Failed to download the package list from https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/istore/Packages.gz

Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/jerryk/Packages.gz
*** Failed to download the package list from https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/jerryk/Packages.gz

Downloading https://mirrors.cloud.tencent.com/lede/releases/18.06.9/packages/aarch64_generic/luci/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_luci
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/packages/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_packages
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/passwall/Packages.gz
*** Failed to download the package list from https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/passwall/Packages.gz

Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/passwall_packages/Packages.gz
*** Failed to download the package list from https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/passwall_packages/Packages.gz

Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/routing/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_routing
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/telephony/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_telephony
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/xiaoxiao29/Packages.gz
*** Failed to download the package list from https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/xiaoxiao29/Packages.gz

Downloading https://istore.linkease.com/repo/all/meta/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_meta
Collected errors:
 * opkg_download: Failed to download https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/helloworld/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/istore/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/jerryk/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/passwall/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/passwall_packages/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_generic/xiaoxiao29/Packages.gz, wget returned 8.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libstdcpp6 and libstdcpp6) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libstdcpp6 and libstdcpp6) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Installing app-meta-routerdog (0.0.19-1) to root...
Downloading https://istore.linkease.com/repo/all/meta/app-meta-routerdog_0.0.19-1_all.ipk
Multiple packages (libstdcpp6 and libstdcpp6) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libstdcpp6 and libstdcpp6) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-md-mod
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-md-mod found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-md-raid0
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-md-raid0 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-md-raid10
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-md-raid10 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-md-raid1
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-md-raid1 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-crypto-hash
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-crypto-null
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-crypto-aead
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-crypto-manager
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885) for kmod-crypto-authenc
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for app-meta-routerdog:
 *      kernel (= 5.15.131-1-3d7f84e6f183df7d8f902d2c548dd885)
 * opkg_install_cmd: Cannot install package app-meta-routerdog.大佬再看一下是什么错误？
 *

**Comment by Carseason** [comment]
核心是你的源里找不到对应的quickstart依赖
也就是istoreos 的默认首页界面那个。对应的github地址是
https://github.com/linkease/nas-packages-luci/tree/main/luci/luci-app-quickstart

**Comment by Carseason** [comment]
https://github.com/Carseason/routerdog/discussions/23
