### ISSUE TITLE
系统更新界面文字排版异常

### ISSUE THREAD

**Issue by hiscatwang** [Carseason/routerdog#7]
系统更新界面文字排版异常
![image](https://github.com/Carseason/routerdog/assets/140864551/bb832bcc-5df3-45db-af87-c9657c37b820)

**Comment by hiscatwang** [comment]
![image](https://github.com/Carseason/routerdog/assets/140864551/a658734a-3ad6-4eb0-88e9-71276726c23c)

**Comment by Carseason** [comment]
图2可以忽略，因为使用了 背景色 来代替 背景图 导致的，上传一份背景图就可以的了 ，没有也不影响
