### ISSUE TITLE
手机端routerdog链接iStoreOS失败

### ISSUE THREAD

**Issue by DBeidachazi** [Carseason/routerdog#9]
我用手机端的routerdog填写正确的路由信息后，首页显示连接正常，但是点进去之后却显示离线帮助
我更改过我的istoreos的首页端口，目前不是80，跟这个有关系吗，还是别的原因
![Screenshot_2023-10-15-21-12-53-127_com example routerapp](https://github.com/Carseason/routerdog/assets/63102882/6c7b4a02-b0bd-4921-b141-37b1fc0eb793)
![Screenshot_2023-10-15-21-12-55-167_com example routerapp](https://github.com/Carseason/routerdog/assets/63102882/a03a141e-779a-4c1f-b441-4b4412c126a2)

**Comment by Carseason** [comment]
你改了端口的话,添加设备的时候也得写上对应的端口才行
